### PR TITLE
Added GEANT particles to event display

### PR DESCRIPTION
**Pull request by AleenaRafique11**

### CODE REVIEW

**Comment by AleenaRafique11** [comment]
Hi,

This is the one that should be used. 

Aleena

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
@AleenaRafique11   lareventdisplay/EventDisplay/SimulationDrawer.cxx has a conflict with the head of develop.  Please make sure your work is consistent with what is now in the head of develop.

**Comment by AleenaRafique11** [comment]
Hi Lynn,

This is my first pull-request and therefore maybe I am not properly familiar with how it is done properly. In my PR, what I did to display GEANT particles on the event display is to change this one file "lareventdisplay/EventDisplay/SimulationDrawer.cxx”. I added some of my additional code to draw GEANT particles.
Now if I look at the conflicts, those are exactly same code lines that I added in order to draw GEANT particles. Now what do you suggest? If other people want to also display GEANT particles and want to use the code that I have, what would be the best way?

Thanks,
Aleena Rafique
Postdoctoral Research Associate
Building 362, Room F-125
Argonne National Laboratory
Lemont, IL 60439
630-252-6281(office)

On Oct 8, 2020, at 3:20 PM, Lynn Garren <notifications@github.com<mailto:notifications@github.com>> wrote:



@AleenaRafique11<https://github.com/AleenaRafique11> lareventdisplay/EventDisplay/SimulationDrawer.cxx has a conflict with the head of develop. Please make sure your work is consistent with what is now in the head of develop.

**Comment by lgarren** [comment]
@AleenaRafique11  I see that you started this branch from larsoft v08_36_02.  That is significantly behind the head of develop.  It is not realistically possible to untangle your changes from other changes that have been made since then.  I suggest that the best course of action is for you to make a fresh PR based on the head of develop and make sure it works as intended with the latest larsoft.

FYI, please note that we still recommend using the feature branch naming convention (feature/<name>_<description>).

**Comment by lgarren** [comment]
@AleenaRafique11   I see that the markup has removed part of my comment.  The feature branch naming convention is feature/yourname_description

**Comment by lgarren** [comment]
Aleena, that seems like a sensible suggestion.  Looking forward to a later PR from you based on the head of develop.

Lynn

**Comment by AleenaRafique11** [comment]
I will do pull-request again once I check out the latest larsoft release based on the head of develop

**Pull request closed without merging**
