### PR TITLE
Added Geant particles to event display

### PR DESCRIPTION
**Pull request by AleenaRafique11**

### CODE REVIEW

**Comment by yangtj207** [comment]
trigger build

**Comment by lgarren** [comment]
@AleenaRafique11  Did you attempt to fix the reported problem in a new PR instead of updating this PR?

**Comment by AleenaRafique11** [comment]
Hi Lynn, 

Yes, I figured that I merged “develop” branch accidentally into my PR and I was unable to compile code from my repository anymore. 

I now fixed the problem in the new PR and the code compiles well in this PR. Please build the code and see if it works this time. Let me know if there are any questions. 

Thanks, 
Aleena

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
@AleenaRafique11  Apologies for being obtuse, but which PR should we be using?  You can close the one you don't want us to use on github.  Just scroll to the bottom of the comments and click on "close with comment".

**Pull request closed without merging**
